openapi: 3.0.0
info:
  title: NeuroBuildTech Device & Data API
  description: |
    Secure RESTful API for IoT device management and sensor data access.
    
    ## Authentication
    This API supports two authentication methods:
    - **JWT Token**: For user and admin access (use `Bearer <token>` in Authorization header)
    - **API Key**: For device access (use `x-api-key` header)
    
    ## Rate Limiting
    - Default: 100 requests per 15 minutes per user/IP
    - Devices: 60 requests per minute
    - Queries: 30 requests per minute
  version: 1.0.0
  contact:
    name: NeuroBuildTech Support
    email: support@neurobuildtech.com

servers:
  - url: http://localhost:3000/api/v1
    description: Development server
  - url: https://api.neurobuildtech.com/api/v1
    description: Production server

tags:
  - name: Devices
    description: Device management operations
  - name: Data
    description: Sensor data operations
  - name: Health
    description: System health and metrics

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    apiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

  schemas:
    Device:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        type:
          type: string
          enum: [sensor_hub, gateway, standalone]
        status:
          type: string
          enum: [active, inactive, maintenance]
        location:
          type: object
          properties:
            building:
              type: string
            floor:
              type: string
            room:
              type: string
        sensors:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum: [ld2410, pir, mq134]
              model:
                type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    SensorReading:
      type: object
      properties:
        id:
          type: string
          format: uuid
        device_id:
          type: string
          format: uuid
        timestamp:
          type: string
          format: date-time
        readings:
          type: array
          items:
            type: object
            properties:
              sensor_type:
                type: string
                enum: [ld2410, pir, mq134]
              values:
                type: object
              quality:
                type: string
                enum: [good, fair, poor]

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            requestId:
              type: string

paths:
  /devices:
    get:
      tags:
        - Devices
      summary: List all devices
      description: Get a paginated list of devices with optional filtering
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: status
          in: query
          schema:
            type: string
            enum: [active, inactive, maintenance]
        - name: type
          in: query
          schema:
            type: string
            enum: [sensor_hub, gateway, standalone]
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      devices:
                        type: array
                        items:
                          $ref: '#/components/schemas/Device'
                      pagination:
                        type: object
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - Devices
      summary: Register new device
      description: Register a new IoT device (admin only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - type
              properties:
                name:
                  type: string
                type:
                  type: string
                  enum: [sensor_hub, gateway, standalone]
                location:
                  type: object
                sensors:
                  type: array
                  items:
                    type: object
      responses:
        '201':
          description: Device created successfully
        '400':
          description: Validation error
        '403':
          description: Insufficient permissions

  /devices/{id}:
    get:
      tags:
        - Devices
      summary: Get device details
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
        '404':
          description: Device not found

    put:
      tags:
        - Devices
      summary: Update device
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Device updated
        '404':
          description: Device not found

    delete:
      tags:
        - Devices
      summary: Deactivate device
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Device deactivated
        '404':
          description: Device not found

  /devices/{id}/status:
    get:
      tags:
        - Devices
      summary: Get device status
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Device status retrieved

  /data/sensors:
    get:
      tags:
        - Data
      summary: Query sensor data
      security:
        - bearerAuth: []
      parameters:
        - name: device_id
          in: query
          schema:
            type: string
            format: uuid
        - name: sensor_type
          in: query
          schema:
            type: string
            enum: [ld2410, pir, mq134]
        - name: start_time
          in: query
          schema:
            type: string
            format: date-time
        - name: end_time
          in: query
          schema:
            type: string
            format: date-time
        - name: limit
          in: query
          schema:
            type: integer
            default: 100
      responses:
        '200':
          description: Sensor data retrieved

  /data/latest:
    get:
      tags:
        - Data
      summary: Get latest readings
      description: Get the most recent reading from each device
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Latest readings retrieved

  /data/submit:
    post:
      tags:
        - Data
      summary: Submit sensor data
      description: Submit sensor readings from a device
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - device_id
                - readings
              properties:
                device_id:
                  type: string
                  format: uuid
                timestamp:
                  type: string
                  format: date-time
                readings:
                  type: array
                  items:
                    type: object
      responses:
        '201':
          description: Data submitted successfully
        '403':
          description: Device can only submit its own data

  /health:
    get:
      tags:
        - Health
      summary: Health check
      description: Check if the API service is running
      responses:
        '200':
          description: Service is healthy
        '503':
          description: Service is degraded

  /metrics:
    get:
      tags:
        - Health
      summary: System metrics
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Metrics retrieved

  /status:
    get:
      tags:
        - Health
      summary: System status
      description: Detailed system status (admin only)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Status retrieved
